public class Map {
    Graph map;
    public void makemap() {
        map =  new Graph();
        map.addVertex("Start");
        for(int i = 1; i<=36; i++){
            map.addVertex(Integer.toString(i));
        }
        map.addVertex("Finish");
        map.insertEdge("Start","1","Bottom");
        map.insertEdge("1","Start","Top");
        map.insertEdge("1","2","Bottom");
        map.insertEdge("2","1","Top");
        map.insertEdge("2","3","Left");
        map.insertEdge("3","2","Right");
        map.insertEdge("3","4","Left");
        map.insertEdge("4","3","Right");
        map.insertEdge("4","5","Top");
        map.insertEdge("4","7","Bottom");
        map.insertEdge("5","4","Bottom");
        map.insertEdge("5","6","Right");
        map.insertEdge("6","5","Left");
        map.insertEdge("7","4","Top");
        map.insertEdge("7","8","Right");
        map.insertEdge("8","9","Right");
        map.insertEdge("8","7","Left");
        map.insertEdge("9","8","Left");
        map.insertEdge("9","10","Bottom");
        map.insertEdge("9","18","Right");
        map.insertEdge("10","9","Top");
        map.insertEdge("10","11","Bottom");
        map.insertEdge("11","10","Top");
        map.insertEdge("11","12","Left");
        map.insertEdge("12","11","Right");
        map.insertEdge("12","13","Top");
        map.insertEdge("13","12","Bottom");
        map.insertEdge("13","14","Left");
        map.insertEdge("14","13","Right");
        map.insertEdge("14","15","Bottom");
        map.insertEdge("15","14","Top");
        map.insertEdge("15","16","Bottom");
        map.insertEdge("16","15","Top");
        map.insertEdge("16","17","Right");
        map.insertEdge("17","16","Left");
        map.insertEdge("18","9","Left");
        map.insertEdge("18","19","Top");
        map.insertEdge("18","25","Right");
        map.insertEdge("19","18","Bottom");
        map.insertEdge("19","20","Top");
        map.insertEdge("20","19","Bottom");
        map.insertEdge("20","21","Right");
        map.insertEdge("21","20","Left");
        map.insertEdge("21","22","Right");
        map.insertEdge("22","21","Left");
        map.insertEdge("22","23","Bottom");
        map.insertEdge("23","22","Top");
        map.insertEdge("23","24","Left");
        map.insertEdge("24","23","Right");
        map.insertEdge("25","18","Left");
        map.insertEdge("25","26","Right");
        map.insertEdge("26","25","Left");
        map.insertEdge("26","27","Bottom");
        map.insertEdge("27","26","Top");
        map.insertEdge("27","28","Left");
        map.insertEdge("28","27","Right");
        map.insertEdge("28","29","Left");
        map.insertEdge("29","28","Right");
        map.insertEdge("29","30","Bottom");
        map.insertEdge("30","29","Top");
        map.insertEdge("30","31","Right");
        map.insertEdge("31","30","Left");
        map.insertEdge("31","32","Right");
        map.insertEdge("32","31","Left");
        map.insertEdge("32","33","Bottom");
        map.insertEdge("33","32","Top");
        map.insertEdge("33","34","Left");
        map.insertEdge("34","33","Right");
        map.insertEdge("34","35","Left");
        map.insertEdge("35","34","Right");
        map.insertEdge("35","Finish","Bottom");
        map.insertEdge("35","36","Left");
        map.insertEdge("36","35","Right");
        map.insertEdge("Finish","35","Top");
    }


}
