import javax.swing.*;
import java.awt.*;

public class Map {
    Graph map;
    public void makemap() {
        Graph map =  new Graph();
        this.map = map;
//        map.addVertex("Start");
//        map.addVertex("1");
//        map.addVertex("3");
//        map.addVertex("2");
//        map.addVertex("4");
//        map.addVertex("5");
//        map.addVertex("6");
//        map.addVertex("7");
//        map.addVertex("8");
//        map.addVertex("9");
//        map.addVertex("10");
//        map.addVertex("11");
//        map.addVertex("12");
//        map.addVertex("13");
//        map.addVertex("14");
//        map.addVertex("15");
//        map.addVertex("16");
//        map.addVertex("17");
//        map.addVertex("18");
//        map.addVertex("19");
//        map.addVertex("20");
//        map.addVertex("21");
//        map.addVertex("22");
//        map.addVertex("23");
//        map.addVertex("24");
//        map.addVertex("25");
//        map.addVertex("Finish");
//
//        map.insertEdge("Start","1",2,"Bottom");
//        map.insertEdge("1","Start",2,"Top");
//        map.insertEdge("1","3",2,"Left");
//        map.insertEdge("2","3",1,"Bottom");
//        map.insertEdge("2","25",1,"Right");
//        map.insertEdge("3","1",2,"Right");
//        map.insertEdge("3","2",1,"Top");
//        map.insertEdge("3","4",1,"Bottom");
//        map.insertEdge("4","3",1,"Top");
//        map.insertEdge("4","5",2,"Right");
//        map.insertEdge("5","4",2,"Left");
//        map.insertEdge("5","6",2,"Bottom");
//        map.insertEdge("5","12",1,"Right");
//        map.insertEdge("6","5",2,"Top");
//        map.insertEdge("6","7",1,"Left");
//        map.insertEdge("7","6",1,"Right");
//        map.insertEdge("7","8",1,"Top");
//        map.insertEdge("8","9",1,"Left");
//        map.insertEdge("8","7",1,"Bottom");
//        map.insertEdge("9","8",1,"Right");
//        map.insertEdge("9","10",2,"Bottom");
//        map.insertEdge("10","11",1,"Right");
//        map.insertEdge("10","9",2,"Top");
//        map.insertEdge("11","10",1,"Left");
//        map.insertEdge("12","5",1,"Left");
//        map.insertEdge("12","13",2,"Top");
//        map.insertEdge("12","17",2,"Right");
//        map.insertEdge("13","12",2,"Bottom");
//        map.insertEdge("13","14",2,"Right");
//        map.insertEdge("14","13",2,"Left");
//        map.insertEdge("14","15",1,"Bottom");
//        map.insertEdge("15","16",1,"Left");
//        map.insertEdge("15","14",1,"Top");
//        map.insertEdge("16","15",1,"Right");
//        map.insertEdge("17","12",2,"Left");
//        map.insertEdge("17","18",1,"Bottom");
//        map.insertEdge("18","17",1,"Top");
//        map.insertEdge("18","19",2,"Left");
//        map.insertEdge("19","18",2,"Right");
//        map.insertEdge("19","20",1,"Bottom");
//        map.insertEdge("20","19",1,"Top");
//        map.insertEdge("20","21",2,"Right");
//        map.insertEdge("21","22",1,"Bottom");
//        map.insertEdge("21","20",2,"Left");
//        map.insertEdge("22","21",1,"Top");
//        map.insertEdge("22","23",2,"Left");
//        map.insertEdge("23","22",2,"Right");
//        map.insertEdge("23","24",1,"Left");
//        map.insertEdge("23","Finish",1,"Bottom");
//        map.insertEdge("24","23",1,"Right");
//        map.insertEdge("25","2",1,"Left");
//        map.insertEdge("Finish","23",1,"Top");
        map.addVertex("Start");
        for(int i = 1; i<=36; i++){
            map.addVertex(Integer.toString(i));
        }
        map.addVertex("Finish");
        map.insertEdge("Start","1",1,"Bottom");
        map.insertEdge("1","Start",1,"Top");
        map.insertEdge("1","2",1,"Bottom");
        map.insertEdge("2","1",1,"Top");
        map.insertEdge("2","3",1,"Left");
        map.insertEdge("3","2",1,"Right");
        map.insertEdge("3","4",1,"Left");
        map.insertEdge("4","3",1,"Right");
        map.insertEdge("4","5",1,"Top");
        map.insertEdge("4","7",1,"Bottom");
        map.insertEdge("5","4",1,"Bottom");
        map.insertEdge("5","6",1,"Right");
        map.insertEdge("6","5",1,"Left");
        map.insertEdge("7","4",1,"Top");
        map.insertEdge("7","8",1,"Right");
        map.insertEdge("8","9",1,"Right");
        map.insertEdge("8","7",1,"Left");
        map.insertEdge("9","8",1,"Left");
        map.insertEdge("9","10",1,"Bottom");
        map.insertEdge("9","18",1,"Right");
        map.insertEdge("10","9",1,"Top");
        map.insertEdge("10","11",1,"Bottom");
        map.insertEdge("11","10",1,"Top");
        map.insertEdge("11","12",1,"Left");
        map.insertEdge("12","11",1,"Right");
        map.insertEdge("12","13",1,"Top");
        map.insertEdge("13","12",1,"Bottom");
        map.insertEdge("13","14",1,"Left");
        map.insertEdge("14","13",1,"Right");
        map.insertEdge("14","15",1,"Bottom");
        map.insertEdge("15","14",1,"Top");
        map.insertEdge("15","16",1,"Bottom");
        map.insertEdge("16","15",1,"Top");
        map.insertEdge("16","17",1,"Right");
        map.insertEdge("17","16",1,"Left");
        map.insertEdge("18","9",1,"Left");
        map.insertEdge("18","19",1,"Top");
        map.insertEdge("18","25",1,"Right");
        map.insertEdge("19","18",1,"Bottom");
        map.insertEdge("19","20",1,"Top");
        map.insertEdge("20","19",1,"Bottom");
        map.insertEdge("20","21",1,"Right");
        map.insertEdge("21","20",1,"Left");
        map.insertEdge("21","22",1,"Right");
        map.insertEdge("22","21",1,"Left");
        map.insertEdge("22","23",1,"Bottom");
        map.insertEdge("23","22",1,"Top");
        map.insertEdge("23","24",1,"Left");
        map.insertEdge("24","23",1,"Right");
        map.insertEdge("25","18",1,"Left");
        map.insertEdge("25","26",1,"Right");
        map.insertEdge("26","25",1,"Left");
        map.insertEdge("26","27",1,"Bottom");
        map.insertEdge("27","26",1,"Top");
        map.insertEdge("27","28",1,"Left");
        map.insertEdge("28","27",1,"Right");
        map.insertEdge("28","29",1,"Left");
        map.insertEdge("29","28",1,"Right");
        map.insertEdge("29","30",1,"Bottom");
        map.insertEdge("30","29",1,"Top");
        map.insertEdge("30","31",1,"Right");
        map.insertEdge("31","30",1,"Left");
        map.insertEdge("31","32",1,"Right");
        map.insertEdge("32","31",1,"Left");
        map.insertEdge("32","33",1,"Bottom");
        map.insertEdge("33","32",1,"Top");
        map.insertEdge("33","34",1,"Left");
        map.insertEdge("34","33",1,"Right");
        map.insertEdge("34","35",1,"Left");
        map.insertEdge("35","34",1,"Right");
        map.insertEdge("35","Finish",1,"Bottom");
        map.insertEdge("35","36",1,"Left");
        map.insertEdge("36","35",1,"Right");
        map.insertEdge("Finish","35",1,"Top");
    }


}
